const SECTION_NAMES = {
  BASIC_CONTENT_SECTION: 'BASIC_CONTENT_SECTION',
  CAREERS_SECTION: 'CAREERS_SECTION',
  CAROUSEL_SECTION: 'CAROUSEL_SECTION',
  CLIENTS_SECTION: 'CLIENTS_SECTION',
  CONTENT_SECTION: 'CONTENT_SECTION',
  CTA_SECTION: 'CTA_SECTION',
  EMPLOYEES_SECTION: 'EMPLOYEES_SECTION',
  FAQ_SECTION: 'FAQ_SECTION',
  HIGHLIGHT_SECTION: 'HIGHLIGHT_SECTION',
  INTRO_BLOCK: 'INTRO_BLOCK',
  IMPACT_SECTION: 'IMPACT_SECTION',
  TIMELINE_SECTION: 'TIMELINE_SECTION',
  USPS_SECTION: 'USPS_SECTION',
  RICH_TEXT_SECTION: 'RICH_TEXT_SECTION',
  TEXT_BLOCK_SECTION: 'TEXT_BLOCK_SECTION',
  AUTHOR_SECTION: 'AUTHOR_SECTION',
  QUOTE_SECTION: 'QUOTE_SECTION',
  VIDEO_SECTION: 'VIDEO_SECTION',
  IFRAME_SECTION: 'IFRAME_SECTION',
  CHECKLIST_CAROUSEL_SECTION: 'CHECKLIST_CAROUSEL_SECTION',
  WHITEPAPER_FORM_SECTION: 'WHITEPAPER_FORM_SECTION',
  RESPONSE_FORM_SECTION: 'RESPONSE_FORM_SECTION'
}

export default SECTION_NAMES
